version: '3.9'

services:

  postgres:
    image: postgres:16
    container_name: postgres-hospital
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: hospital

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  mongo:
    image: mongo:8
    container_name: mongo-hospital
    restart: always

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data: